/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 03 18:25:52 EET 2016
 */


import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class CourseQuerySystem_ESTest extends CourseQuerySystem_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      CourseQuerySystem courseQuerySystem0 = new CourseQuerySystem();
  }
}
