/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 03 18:27:15 EET 2016
 */


import static org.junit.Assert.assertEquals;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class Instructor_ESTest extends Instructor_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      Instructor instructor0 = new Instructor("", "", true);
      instructor0.surname = "";
      String string0 = instructor0.toString();
      assertEquals(" Name :  Surname:  isPrimary: true", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      Instructor instructor0 = new Instructor("", "", true);
      instructor0.surname = "";
      String string0 = instructor0.instructorName();
      assertEquals(" ", string0);
  }

  @Test
  public void test2()  throws Throwable  {
      Instructor instructor0 = new Instructor("  Surname: ", (String) null, true);
  }
}
