/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 03 18:28:03 EET 2016
 */


import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class MeetingTime_ESTest extends MeetingTime_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      Room room0 = new Room();
      MeetingTime meetingTime0 = new MeetingTime("", "w0~.s8N0t4bk@qJ", "", room0);
      meetingTime0.finishHour = "";
      // Undeclared exception!
      try { 
        meetingTime0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("Room", e);
      }
  }

  @Test
  public void test1()  throws Throwable  {
      MeetingTime meetingTime0 = new MeetingTime((String) null, "w0~.s8N0t4bk@qJ", "QugF@E.'e;", (Room) null);
  }

  @Test
  public void test2()  throws Throwable  {
      MeetingTime meetingTime0 = new MeetingTime();
  }
}
