/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 03 18:28:42 EET 2016
 */


import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import java.util.ArrayList;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class Room_ESTest extends Room_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Room room0 = new Room(arrayList0);
      String string0 = room0.toString();
      assertEquals(" Room: []", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      Room room0 = new Room();
      // Undeclared exception!
      try { 
        room0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("Room", e);
      }
  }
}
