/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 03 18:34:48 EET 2016
 */


import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.fail;

import java.util.ArrayList;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class StudentAdder_ESTest extends StudentAdder_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      ArrayList<Course> arrayList0 = new ArrayList<Course>();
      ArrayList<Student> arrayList1 = new ArrayList<Student>();
      StudentAdder studentAdder0 = new StudentAdder(arrayList0, arrayList1);
      ArrayList<Course> arrayList2 = studentAdder0.courseDataList;
      assertSame(arrayList0, arrayList2);
  }

  @Test
  public void test1()  throws Throwable  {
      ArrayList<Course> arrayList0 = new ArrayList<Course>();
      int int0 = (-1);
      ArrayList<Student> arrayList1 = null;
      try {
        arrayList1 = new ArrayList<Student>((-1));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal Capacity: -1
         //
         assertThrownBy("java.util.ArrayList", e);
      }
  }
}
